### ISSUE TITLE
Disable forwarding

### ISSUE THREAD

**Issue by RomanSilinenko** [0x4d4c/inetsim-dockerized#2]
The image has unpleasant flaw.
If lab host does direct http request to an IP address, without resolving DNS, the container will silently forward the request to the target destination.

**Comment by 0x4d4c** [comment]
Hi and thanks for reporting. I think I need some more information to debug this. Could you tell me how your setup looks like and how your query looks like? Is it really the container that forwards the request or is the request forwarded by routing decisions taking place before the request reaches the container?

**Comment by RomanSilinenko** [comment]
Hi. The env is configured as following.
There's a shared bridge which is created as a standard docker installation and where regular containers obtain its network settings. And in parallel i run a qcow VM which is also connected the the same bridge. So effectively intetsim contained and VM share the same network. Now, in VM settings i set Inetsim docker container as a default gateway and as DNS server. 
So with such setting, inside of VM if i go to some fqdn (http://acme.com) i end up with Inetsim fake http server. But if i request something like http://<ip.addres>/ im routed throught the Inetsim into the wild. 
So to adhoc fix it I have to manually add iptables rules to block outgoing traffic. Although now i am already no so sure it is possible to turn off ip_forwarding in the container at all. it seems to be the host's feature...

**Comment by 0x4d4c** [comment]
I finally managed to find some time to reproduce you setup and I think I found the problem. In my tests I noticed that the container sends ICMP redirects when being used as a gateway. If your VM accepts these redirects, it will continue to use whatever your container has configured as a gateway. This does not happen when DNS is used because I guess you configured INetSim to return its own IP for all DNS queries it receives.

Could you please check whether a ping from the VM to an IP that you did not contact before returns something like `Redirect Host (New nexthop ...)`?

Unfortunately, this would be something that is not fixable in the container image. Still, you can disable this behavior either by setting `net.ipv4.conf.*.accept_redirects` to `0` in your VM (`sysctl -w net.ipv4.conf.all.accept_redirects=0` and `sysctl -w net.ipv4.conf.YOUR_IF.accept_redirects=0`) or by starting the container with `net.ipv4.conf.*.send_redirects` set to `0` (`docker run --sysctl net.ipv4.conf.all.send_redirects=0 --sysctl net.ipv4.conf.eth0.send_redirects=0 ...`). Note that you probably have to set this parameter to both `all` and the name of your network interface to really turn off the redirects.

In my tests one of the above solutions made the VM stop using the Docker gateway to access the Internet. Could you please check if this works for you, too?

**Comment by RomanSilinenko** [comment]
Hi. Thanks for investigation. I guess running the container with additional sysctl keys is pretty working solution.
